"""Project manifest (`lang.toml`) and lockfile (`lang.lock`).

Manifest format (SPEC-020):

    [project]
    name = "localflow"
    mode = "draft"          # or "verified": default acceptance mode (V3 5.15.1)

    [dependencies]
    util = { path = "../util" }   # pinned local dependency

The lockfile records each dependency's resolved path and a content hash. Imports may
only reach the project, the standard library (`std.*`), and pinned dependencies; an
import of anything else is `S.MODULE.UNKNOWN_DEPENDENCY` (V3 5.16.4: a hallucinated
package name cannot alter the dependency graph).
"""
from __future__ import annotations

import hashlib
import os
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class Dependency:
    name: str
    path: Path
    locked_hash: Optional[str] = None


@dataclass
class Project:
    root: Path
    name: str = "main"
    mode: str = "draft"
    dependencies: dict[str, Dependency] = field(default_factory=dict)
    manifest_path: Optional[Path] = None
    problems: list[str] = field(default_factory=list)


def find_project_root(start: Path) -> Optional[Path]:
    p = start if start.is_dir() else start.parent
    p = p.resolve()
    for cand in [p, *p.parents]:
        if (cand / "lang.toml").exists():
            return cand
    return None


def load_project(entry: Path) -> Project:
    root = find_project_root(entry)
    if root is None:
        base = entry.parent if entry.is_file() or entry.suffix else entry
        return Project(root=base.resolve())
    manifest = root / "lang.toml"
    proj = Project(root=root, manifest_path=manifest)
    try:
        data = tomllib.loads(manifest.read_text())
    except (tomllib.TOMLDecodeError, OSError) as e:
        proj.problems.append(f"cannot read {manifest}: {e}")
        return proj
    meta = data.get("project", {})
    proj.name = str(meta.get("name", root.name))
    mode = str(meta.get("mode", "draft"))
    if mode not in ("draft", "verified"):
        proj.problems.append(f"project.mode must be 'draft' or 'verified', got {mode!r}")
        mode = "draft"
    proj.mode = mode
    deps = data.get("dependencies", {})
    lock = read_lock(root)
    for name, spec in deps.items():
        if not isinstance(spec, dict) or "path" not in spec:
            proj.problems.append(f"dependency {name!r} must be {{ path = \"...\" }}")
            continue
        dep_path = (root / spec["path"]).resolve()
        proj.dependencies[name] = Dependency(name, dep_path, lock.get(name))
        if not dep_path.exists():
            proj.problems.append(f"dependency {name!r} path {dep_path} does not exist")
        elif name not in lock:
            proj.problems.append(f"dependency {name!r} is not recorded in lang.lock (run `lang lock`)")
        elif lock[name] != tree_hash(dep_path):
            proj.problems.append(f"dependency {name!r} content differs from lang.lock (run `lang lock` after review)")
    return proj


def read_lock(root: Path) -> dict[str, str]:
    lock = root / "lang.lock"
    if not lock.exists():
        return {}
    try:
        data = tomllib.loads(lock.read_text())
    except tomllib.TOMLDecodeError:
        return {}
    return {k: v.get("hash", "") for k, v in data.get("dependency", {}).items() if isinstance(v, dict)}


def tree_hash(path: Path) -> str:
    h = hashlib.sha256()
    for dirpath, dirnames, filenames in sorted(os.walk(path)):
        dirnames.sort()
        for fn in sorted(filenames):
            if fn.endswith(".lang") or fn == "lang.toml":
                fp = Path(dirpath) / fn
                h.update(str(fp.relative_to(path)).encode())
                h.update(fp.read_bytes())
    return h.hexdigest()[:16]


def write_lock(project: Project) -> str:
    lines = ["# generated by `lang lock`; review changes like source edits", ""]
    for name, dep in sorted(project.dependencies.items()):
        lines.append(f"[dependency.{name}]")
        lines.append(f'path = "{os.path.relpath(dep.path, project.root)}"')
        lines.append(f'hash = "{tree_hash(dep.path)}"')
        lines.append("")
    text = "\n".join(lines)
    (project.root / "lang.lock").write_text(text)
    return text
